- name: Redémarrer smartctl_exporter
  ansible.builtin.systemd_service:
    name: smartctl_exporter
    state: restarted
    daemon_reload: true

- name: Redémarrer l'envoi du journal
  ansible.builtin.systemd_service:
    name: systemd-journal-upload
    state: restarted
    daemon_reload: true
